version: '2.2'

services:

  ############## Internal Network ###############

  employee_fakebank:
    cap_add:
      - NET_ADMIN
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
    hostname: employee
    image: employeelab:1.0
    networks:
      - vlan
    volumes:
      - ./employee/resolv.conf:/etc/resolv.conf

  
  mail_fakebank:
    cap_add:
      - NET_ADMIN
    environment:
      - DOMAIN=fakebank.lab
      - THEME_INDEX=6
      - APP_NAME=Fake Bank
      - USER_TYPE=1
      - EMAIL_GATEWAY=internet.lab|smtp:172.20.20.50
    image: webmaillab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.10


  site:
    cap_add:
      - NET_ADMIN
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
      - DATABASE_CONNECTION_STRING=Host=172.20.20.30;Port=5432;Pooling=true;Database=site;User Id=site;Password=123
      - EMAIL_SERVER=172.20.20.10
      - EMAIL_USER=admin
      - EMAIL_PASSWORD=admin
      - EMAIL_USE_DEFAULT_CREDENTIALS=false
      - EMAIL_CONTACT=contato@fakebank.lab
      - EMAIL_SENDER=site@fakebank.lab
    hostname: site
    image: sitelab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.20

  database_fakebank:
    cap_add:
      - NET_ADMIN
    hostname: site
    image: databaselab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.30


  dns_fakebank:
    cap_add:
      - NET_ADMIN
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
    image: dnslab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.80
    volumes:
      - ./dns/dns-int.json:/root/config.json


  proxy_fakebank:
    cap_add:
      - NET_ADMIN
    environment:
      - EMAIL_GATEWAY=internet.lab|smtp:172.30.30.10;fakebank.lab|smtp:172.20.20.10
    image: proxylab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.50
      external:
        ipv4_address: 172.30.30.50
    volumes:
      - ./proxy/squid.conf:/etc/squid/squid.conf    
    sysctls:
      - net.ipv4.ip_forward=0

  ############## External Network ###############

  mail_internet:
    cap_add:
      - NET_ADMIN
    environment:
      - DOMAIN=internet.lab
      - THEME_INDEX=17
      - USER_TYPE=2
      - APP_NAME=Internet Mail
      - EMAIL_GATEWAY=fakebank.lab|smtp:172.30.30.50
    image: webmaillab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.10

  dns_internet_p:
    image: dnslab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.80
    volumes:
      - ./dns/dns-ext-p.json:/root/config.json
  
  dns_internet_s:
    image: dnslab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.90
    volumes:
      - ./dns/dns-ext-s.json:/root/config.json
  
  threat_internet:
    hostname: threat
    image: threatlab:1.0
    networks:
      - external
    volumes:
      - ./threat/resolv.conf:/etc/resolv.conf

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 172.20.20.0/24
          gateway: 172.20.20.254
          ip_range: 172.20.20.128/25
      driver: default

  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24