version: '2'

services:

  ############ Company

  employee:
    cap_add:
      - NET_ADMIN
    hostname: employee
    networks:
      - internal
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
    image: employeelab:1.0
    volumes:
      - ./employee/resolv.conf:/etc/resolv.conf

  mail_company:
    cap_add:
      - NET_ADMIN
    environment:
      - DOMAIN=fakebank.lab
      - DEFAULT_GATEWAY=172.20.20.50
    image: webmaillab:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.10

  dns_company:
    cap_add:
      - NET_ADMIN
    image: dnslab:1.0
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
    networks:
      internal:
        ipv4_address: 172.20.20.80
    volumes:
      - ./dnsserver/dns-int.json:/root/config.json

  proxy_company:
    cap_add:
      - NET_ADMIN
    image: proxylab:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.50
      external:
        ipv4_address: 172.30.30.50

  ######### Internet

  mail_internet:
    cap_add:
      - NET_ADMIN
    image: webmaillab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.10
    environment:
      - DOMAIN=internet.lab

  dns_internet:
    image: dnslab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.80
    volumes:
      - ./dnsserver/dns-ext.json:/root/config.json
  
  threat:
    image: threatlab:1.0
    hostname: threat
    networks:
      - external
    volumes:
      - ./threat/resolv.conf:/etc/resolv.conf

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24