version: '2'

services:
  mail:
    image: squirrelmail:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.10
  dns:
    image: binddns:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.80
    volumes:
      - ./dnsserver/config.json:/root/config.json
  proxy:
    image: squidproxy:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.50
      external:
        ipv4_address: 172.30.30.50
  threat:
    image: threat:1.0
    hostname: threat
    networks:
      - external
    volumes:
      - ./threat/resolv.conf:/etc/resolv.conf

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24