version: '2.2'

services:

  ############ Company

  employee:
    cap_add:
      - NET_ADMIN
    hostname: employee
    networks:
      - vlan
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
    image: employeelab:1.0
    volumes:
      - ./employee/resolv.conf:/etc/resolv.conf

  mail_company:
    cap_add:
      - NET_ADMIN
    environment:
      - DOMAIN=fakebank.lab
      - THEME_INDEX=6
      - APP_NAME=Fake Bank
    image: webmaillab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.10

  dns_company:
    cap_add:
      - NET_ADMIN
    image: dnslab:1.0
    environment: 
      - DEFAULT_GATEWAY=172.20.20.50
    networks:
      vlan:
        ipv4_address: 172.20.20.80
    volumes:
      - ./dns/dns-int.json:/root/config.json

  proxy_company:
    cap_add:
      - NET_ADMIN
    image: proxylab:1.0
    networks:
      vlan:
        ipv4_address: 172.20.20.50
      external:
        ipv4_address: 172.30.30.50
    volumes:
      - ./proxy/squid.conf:/etc/squid/squid.conf    
    sysctls:
      - net.ipv4.ip_forward=0

  ######### Internet

  mail_internet:
    cap_add:
      - NET_ADMIN
    image: webmaillab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.10
    environment:
      - DOMAIN=internet.lab
      - THEME_INDEX=17
      - USER_TYPE=2
      - APP_NAME=External Mail

  dns_internet:
    image: dnslab:1.0
    networks:
      external:
        ipv4_address: 172.30.30.80
    volumes:
      - ./dns/dns-ext.json:/root/config.json
  
  threat:
    image: threatlab:1.0
    hostname: threat
    networks:
      - external
    volumes:
      - ./threat/resolv.conf:/etc/resolv.conf

networks:
  vlan:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 172.20.20.0/24
          gateway: 172.20.20.254
          ip_range: 172.20.20.128/25
      driver: default

  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24