version: '2'

services:

  ############ Company
  mail_company:
    image: squirrelmail:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.10
    environment:
      - DOMAIN=fakebank.lab

  dns_company:
    image: binddns:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.80
    volumes:
      - ./dnsserver/dns-int.json:/root/config.json

  proxy_company:
    image: squidproxy:1.0
    networks:
      internal:
        ipv4_address: 172.20.20.50
      external:
        ipv4_address: 172.30.30.50

  ######### Internet

  mail_internet:
    image: squirrelmail:1.0
    networks:
      external:
        ipv4_address: 172.30.30.10
    environment:
      - DOMAIN=internet.lab

  dns_internet:
    image: binddns:1.0
    networks:
      internal:
        ipv4_address: 172.30.30.80
    volumes:
      - ./dnsserver/dns-ext.json:/root/config.json
  
  threat:
    image: threat:1.0
    hostname: threat
    networks:
      - external
    volumes:
      - ./threat/resolv.conf:/etc/resolv.conf

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.20.0/24
  external:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.30.0/24